const data = {
    products:[
        {
            _id: '1',
            name: 'iPhone XR',
            category: 'Mobiles',
            image: '/images/p1.jpg',
            price: '36,000/-',
            brand: 'iphone',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'iPhone XR',
            category: 'Mobiles',
            image: '/images/p1.jpg',
            price: '36,000/-',
            brand: 'iphone',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'iPhone XR',
            category: 'Mobiles',
            image: '/images/p1.jpg',
            price: '36,000/-',
            brand: 'iphone',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'iPhone XR',
            category: 'Mobiles',
            image: '/images/p1.jpg',
            price: '36,000/-',
            brand: 'iphone',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'iPhone XR',
            category: 'Mobiles',
            image: '/images/p1.jpg',
            price: '36,000/-',
            brand: 'iphone',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'iPhone XR',
            category: 'Mobiles',
            image: '/images/p1.jpg',
            price: '36,000/-',
            brand: 'iphone',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
    ],
};
export default data;